[build]
  command = "npm run build"
  publish = "dist"
  base = "/proyecto-universitario"

[[redirects]]
  from = "/*"
  to = "/proyecto-universitario/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

