[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/proyecto-universitario/*"
  to = "/proyecto-universitario/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/proyecto-universitario/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
